### ISSUE TITLE
Timeout type

### ISSUE THREAD

**Issue by SebastienDorgan** [appleboy/easyssh-proxy#35]
Hello Again,

In the MakeConfig struct Timeout is a time.Duration but in Run and Stream method timeout parameter is an int, don't you think it will be better to make every timeout a time.Duration?
If you want I can create a Pull Request.

Sebastien

**Comment by appleboy** [comment]
@SebastienDorgan PR welcome 👍

**Comment by SebastienDorgan** [comment]
I have created a branch 'sd' with the modifications but I am not allowed to commit.

**Comment by appleboy** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by SebastienDorgan** [comment]
ok, done from a my fork

**Comment by appleboy** [comment]
fixed in https://github.com/appleboy/easyssh-proxy/pull/37
