### ISSUE TITLE
Read/write timeout connection

### ISSUE THREAD

**Issue by impr0ver** [appleboy/easyssh-proxy#90]
Need to add in config readtimeout and writetimeout. This will avoid situations where the connection is established, but nothing further happens, and the console freezes. This can happen if the port on the remote server is open, but there is no ssh!

**Comment by impr0ver** [comment]
https://stackoverflow.com/questions/31554196/ssh-connection-timeout

**Comment by appleboy** [comment]
We support the `Timeout` flag. https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig.Timeout
